version: "2"
run:
  timeout: 5m
  tests: false
linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - misspell
    - unconvert
    - unparam
linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (io.Closer).Close
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteString
      - (*strings.Builder).WriteString
      - os.Remove
      - os.RemoveAll
      - os.MkdirAll
  misspell:
    locale: US
issues:
  uniq-by-line: true
  exclude-rules:
    - source: '_test\.go'
      linters:
        - gosec
      text: G304
      reason: Test fixtures load from local paths
    - source: '_test\.go'
      linters:
        - errcheck
      reason: Cleanup helpers in tests intentionally ignore errors
